### ISSUE TITLE
Where can I get the data set address

### ISSUE THREAD

**Issue by zxhjames** [cure-lab/SCINet#10]
I am very interested in your baseline model research. Can you provide the download address of the complete data set in the paper?

**Comment by ailingzengzzz** [comment]
Hi @zxhjames ,
Thanks for your interest in our work. The dataset can be downloaded by one-line command.
```
source prepare_data.sh
```
You can also find this guidance in README -> Dataset preparation.

**Comment by zxhjames** [comment]
thank you very much
