### ISSUE TITLE
您好，请问如果输入加入位置编码是否对预测效果有加成？

### ISSUE THREAD

**Issue by yangye19960922** [cure-lab/SCINet#11]
作者您好，我看您SCINet代码中有positional encoding 模块，想请问一下这个位置编码是否和transformer的一样，以及为什么在预测financial四个数据集的时候，parser.add_argument('--positionalEcoding', type = bool , default=False)
位置编码设置为FALSE，是因为添加位置编码有负面作用么

感谢您的回复

**Comment by ailingzengzzz** [comment]
Hi @yangye19960922 ,
The positional encoding is the same as in the transformer, and you can refer to the model/SCINet.py for more details.
Empirically, We use the positional encoding in PEMS datasets. For other datasets, we found this operation is not helpful.
