### ISSUE TITLE
May I ask whether the algorithm has been updated? Will the content of to-do items be updated this quarter?

### ISSUE THREAD

**Issue by chenruhai** [cure-lab/SCINet#12]
Hello, great author,May I ask whether the algorithm has been updated? Will the content of to-do items be updated this quarter?
Thank you for making open source so everyone can learn.

**Comment by ailingzengzzz** [comment]
Hi @chenruhai ,

Thanks for your interest in our work! We are preparing the to-do items, and they will be coming soon.

**Comment by chenruhai** [comment]
> Hi @chenruhai ,
> 
> Thanks for your interest in our work! We are preparing the to-do items, and they will be coming soon.

Great authors, looking forward to your updates. My brain is starving.
