### ISSUE TITLE
Confusion about ETTh dataloader

### ISSUE THREAD

**Issue by renebidart** [cure-lab/SCINet#13]
Hello, I was confused looking at your code for the ETTh dataloader. There is a variable length_len that is normally set to the same length as the prediction, so the y value will have some overlap with the x value. Could you please let me know the purpose of this length_len and if this overlap will cause issues with evaluation? Thanks!

https://github.com/cure-lab/SCINet/blob/03ab7ff6da4626aaf2809d16931919fd4de4b721/data_process/etth_data_loader.py#L83

**Comment by AlexMinhao** [comment]
Hi, 
 
Thanks for your interest in our work!  As you can see in the [https://github.com/cure-lab/SCINet/blob/03ab7ff6da4626aaf2809d16931919fd4de4b721/experiments/exp_ETTh.py#L402](url), we only supervise the desired part. Therefore, there is no overlap between the input and the future horizon.

**Comment by AlexMinhao** [comment]
Hi,

Thanks for your interest in our work! 
As you can see in the https://github.com/cure-lab/SCINet/blob/03ab7ff6da4626aaf2809d16931919fd4de4b721/experiments/exp_ETTh.py#L402, we only supervise the desired part. Therefore, there is no overlap between the input and the future horizon.
