### ISSUE TITLE
您好，关于文章内容有一个问题想咨询一下

### ISSUE THREAD

**Issue by yangye19960922** [cure-lab/SCINet#15]
关于文章SCI-Block中公式（1）（2）有两个问题想和您讨论一下：
【1】公式（1）中使用exp的原因是什么？是否是单纯将数据映射到一个理想的数值区间还是说是其他原因？
【2】为什么公式（2）中单纯的加减就可以实现下采样信息损失的弥补？
因为我对卷积了解不是甚多，所以对这两个公式的理解还不到位，希望作者可以从百忙之中答疑解惑。Thanks~

**Comment by VEWOXIC** [comment]
您好，感谢您对我们工作的关注。

1.  公式（1）中使用exp是为了增加函数的非线性成分，我们发现这样有利于网络训练。
2.  弥补信息损失不是单纯的依靠公式（2），而是依赖整个交互式学习机制。 在SCI-Block中，通过降采样得到的两段子序列，实际上都还保留了原始序列的绝大部分信息。之后，我们利用不同的卷积核来分别处理两段子序列是为了能同时提取其中包含的同质和异质信息。最后，为了融合提取到的两个子序列的信息，以生成对下游任务更有效的表示，我们提出了本文的交互式学习机制。 交互式学习方案是由公式(1)(2)共同组成的简单的仿射变换(f(x) = Ax +b)来实现的，该方式训练简单，效果良好。

希望以上的信息能够帮助您更好的理解我们的论文！
