### ISSUE TITLE
data scaler in etth_data_loader.py

### ISSUE THREAD

**Issue by PhoebeChen123** [cure-lab/SCINet#16]
train_data = df_data[border1s[0]:border2s[0]]
self.scaler.fit(train_data.values)
data = self.scaler.transform(df_data.values)

Here, why the mean and var of train data are computed to scale all the data?

**Comment by AlexMinhao** [comment]
Hi,

Since we can't get the whole data in advance during the online prediction, only training data is available for calculating mean and std when scaling data. Thanks.
