### ISSUE TITLE
您好，关于interact-learning模块有一个疑惑想请教一下

### ISSUE THREAD

**Issue by yangye19960922** [cure-lab/SCINet#17]
作者您好，关于四个interact-learning模块的细节，我有一个问题想请教一下，我看您的模块中加入了两个一维卷积，并且加入了hidden size的参数，想请问一下加入两个卷积的出发点是什么，他有什么实质性的作用呢？感谢您的回答~

**Comment by VEWOXIC** [comment]
您好, 我们使用两个不同的卷积核的目的是为了使模型能够同时提取两个子序列中的同质和异质的信息, 以期能使模型能够从下采样中受益. 
如果您还有其他问题, 我们乐意继续解答.
