### ISSUE TITLE
Questions about your to-do list?

### ISSUE THREAD

**Issue by CLoweW** [cure-lab/SCINet#19]
Hello, great author, does the content of the to-do list increase much for SCINET? When is the update expected? I was so excited about your algorithm. It blew my mind! I'm trying to study your paper.

**Comment by VEWOXIC** [comment]
Hi! Thanks for your attention! 
Currently, we are working on these two topics and we have made some progress so far. We have developed a series of graph-based methods and they are still being polished. The graph-based part will be released next month if it goes well. For the probabilistic part, we have realized a method to generate probability prediction based on SCINet. We will update this part as soon as possible! 
If you have further questions, please feel free to contact us! Thanks

**Comment by CLoweW** [comment]
> Hi! Thanks for your attention! Currently, we are working on these two topics and we have made some progress so far. We have developed a series of graph-based methods and they are still being polished. The graph-based part will be released next month if it goes well. For the probabilistic part, we have realized a method to generate probability prediction based on SCINet. We will update this part as soon as possible! If you have further questions, please feel free to contact us! Thanks

Come on, big man! I look forward to your work.
