### ISSUE TITLE
Questions about training time

### ISSUE THREAD

**Issue by MatthewYZhang** [cure-lab/SCINet#20]
Hi all,

Appreciate your work. 

I tried to train using the following command, and I noticed that it may take about 10 minutes to train only one epoch. I am using V100 to train.
```
python run_financial.py --dataset_name electricity --window_size 168 --horizon 24 --hidden-size 8 --single_step 1 --stacks 2 --levels 3 --lr 9e-3 --dropout 0 --batch_size 32 --model_name ele_I168_o24_lr9e-3_bs32_dp0_h8_s2l3_w0.5 --groups 321
```
I wonder if this is normal, because as far as I am concerned, your network mainly consists of conv1d and sampling, and they may not took that much time if  If you can kindly offer some training specs and training time, I would be very thankful.

Matthew

**Comment by ailingzengzzz** [comment]
Hi @MatthewYZhang ,

It's normal.
In the "electricity" dataset, we regard it as a univariate dataset. Thus, we use "--groups 321" (321 is the number of variates) in the arguments to split the spatial influence on different varieties. This operation is also known as a “depthwise convolution”, and it will take a longer time to be processed.
