### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by mayankagrawal-quantiphi** [cure-lab/SCINet#26]
Hi,
Can you please guide on how do I train a model on my own custom dataset ?

Thanks for your help!

**Comment by VEWOXIC** [comment]
We recommend you to reformat your dataset as the ETT dataset. Thus, you can directly use the ETT dataloader with only a little tweaks. Also, please make sure you set the data channel as your dataset before initializing the SCINet. 

Thanks for your attention.

**Comment by VEWOXIC** [comment]
If there is no further query. We will close this issue. 
Thanks for your attention.

**Comment by VEWOXIC** [comment]
If there is no further query. We will close this issue.
Thanks for your attention.

**Comment by mayankagrawal-quantiphi** [comment]
Thanks @VEWOXIC! That worked for me
