### ISSUE TITLE
'Tensor' object has no attribute 'dtpye'

### ISSUE THREAD

**Issue by Jiahui-Gu** [cure-lab/SCINet#28]
hello, I got an error

> Traceback (most recent call last):
>   File "run_pems.py", line 87, in <module>
>     _, normalize_statistic = exp.train()
>   File "D:\gjh\workspace\SCINet\experiments\exp_pems.py", line 278, in train
>     forecast = self.model(inputs)
>   File "C:\Users\dell\anaconda3\envs\scinet\lib\site-packages\torch\nn\modules\module.py", line 889
> , in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "D:\gjh\workspace\SCINet\models\SCINet.py", line 355, in forward
>     output = torch.zeros(x.shape,dtype=x.dtpye).cuda()
> AttributeError: 'Tensor' object has no attribute 'dtpye'

when I was running 

> python run_pems.py --dataset PEMS03 --hidden-size 0.0625 --dropout 0.25 --model_name pems03_h0.0625_dp0.25 --num_decoder_layer 2

I use below command build my environment

> conda create -n scinet python=3.8 
> conda activate scinet
> pip install -r requirements.txt (without pytorch)
> conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch -y

How can I solve this problem? Thanks！

**Comment by VEWOXIC** [comment]
Hello, It seems like the 'dtpye' is a typo, please try changing it into 'dtype'.

**Comment by VEWOXIC** [comment]
We have fixed this typo in the repo. If there is no further query. We will close this issue. 
Thanks for your attention.
