### ISSUE TITLE
How to run SCINet on a custom dataset ?

### ISSUE THREAD

**Issue by vinayakrajurs** [cure-lab/SCINet#30]
Hello again,
What are the changes to be made in run_ETTh.py, exp_ETTh.py and etth_data_loader.py to be able to fit this custom dataset and successfully run the code targeting Voltage
Dataset to be used :
[dataset4.csv](https://github.com/cure-lab/SCINet/files/8253818/dataset4.csv)

Thank You in advance

**Comment by VEWOXIC** [comment]
It seem that your dataset have similar format of the ETT dataset. It should works fine with the ETT dataloader (maybe some minor tweaks are needed). But your dataset has less data-channels, please make sure change the input channel of SCINet before initializing it. 

Thanks for your attention.

**Comment by vinayakrajurs** [comment]
good day,
I've figured it and was able to do so.
thank you so much
