### ISSUE TITLE
Seperate testing script

### ISSUE THREAD

**Issue by SaiJaswanthBehara** [cure-lab/SCINet#31]
Hi, i couldn't find a way only to run the testing part without running the entire flow. Is there any way to do this?

**Comment by VEWOXIC** [comment]
Hi. You can always call the `predict` function of the experiment class (in `./experiment/exp_xxx.py`) to load an existing trained model and perform prediction. Or you can add a line of loading state_dict file in the test function and perform the test on it. 

If your have further quentions, please feel free to contact us.

**Comment by VEWOXIC** [comment]
If there is no further query, we will close this issue. 
Thanks for your attention.
