### ISSUE TITLE
Some questions about the results of the PEMS dataset

### ISSUE THREAD

**Issue by liuaoy** [cure-lab/SCINet#32]
Hello, your work is very rewarding! But I had some deviations in the MAE, MAPE, RMSE metrics when I performed the replication on the PEMS dataset, and I only used the model part of the code you provided. When using your code completely, MAE, MAPE, RMSE and the results in the paper are about the same, so I would like to ask you if you use any tips in data preprocessing.

**Comment by liuaoy** [comment]
You mentioned using the same settings as StemGNN, what are the exact operations of these settings? Also, if I use only the code of your model part during training, it may only take 15s. if I use your code completely (including data reading, training code), the training time will be twice as long, so is there some operation in data processing, looking forward to your reply!

**Comment by ailingzengzzz** [comment]
Hi @liuaoy,

We used the same data preprocessing as previous works shown in our repo [function in the experiments/exp_pems.py#L59]. Data preprocessing will take some time. You can use [time()] to calculate the processing time of each part.
