### ISSUE TITLE
ETTH result cannot be reproduced

### ISSUE THREAD

**Issue by ariellin10** [cure-lab/SCINet#33]
Hi, I wonder the result on ETTH dataset in paper, are they  Normed or Denormed?
If they were denormed, the difference between my result and the paper is too large.
This is my result, is this correct?  (I used the latest version code)
Final mean normed mse:0.3660,mae:0.3998
denormed mse:8.2375,mae:1.5608

**Comment by mixiancmx** [comment]
Hi, in the paper, we use normed mse. Your result is correct.

**Comment by ariellin10** [comment]
Thanks!
