### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'dtpye'

### ISSUE THREAD

**Issue by 1506355445** [cure-lab/SCINet#35]
models\SCINet.py", line 355, in forward output = torch.zeros(x.shape,dtype=x.dtpye).cuda()
dtype=x.dtype

**Comment by VEWOXIC** [comment]
Sorry, this is a typo, please change the x.dtpye as x.dtype. 
We have fixed the typo in this file. 
Thanks for your attention.

**Comment by VEWOXIC** [comment]
Sorry, this is a typo, please change the `x.dtpye` as `x.dtype`.
We have fixed the typo in this file.
Thanks for your attention.
