### ISSUE TITLE
Multi Input Single Output Net

### ISSUE THREAD

**Issue by acivit** [cure-lab/SCINet#36]
Hello!

I'm in a situation where I have to predict the future value of a variable that highly depends on another one, as I've seen in the state of the art, there exist models that take into account the future value from those exogenous variables to predict the future value of the desired variable. 

For example: I want to predict the heart beat frequency taking into account the activity that the user will be doing at the future. 

The first idea that came into my mind was to use the 'MS' feature (multi input single value I understood) value from your code instead of 'M' or 'S', to check if the model would learn it implicitly. 

The problem is that I think the option 'MS' is not implemented completely, am I wrong? 

In case that I wanted to develop it, which strategy do you think I should use, where should I start? Do you think it will work properly? Will it be hard to implement that condition? 

Thanks in advance! 

Aniol

**Comment by VEWOXIC** [comment]
Hi Aniol, 

We did not implement the 'MS' feature option. The only options are 'M' (multi-channel in multi-channel out) and 'S' (single-channel in single-channel out). 

In my understanding, you want to predict the heart beat of t0~t0+t with the help of some exogenous variables of this period of time. I think the first thing you need to fiture out is that how to make use of the information in these data. Maybe you can use a seperate encoder (SCINet encoder is okay) to extract the temporal feature and fuse (concat or add) it with the prediction feature. And finally use a decoder to decode it. Then you can train this model en-2-end-ly. You may need to tweak the dataloader in this case. 

This is just some of my ideas. Hope this can help you. 

Sincerely
Zhijian

**Comment by VEWOXIC** [comment]
If there is no further question, I will close this issue now. 
Please feel free to reopen it if you still need any help. :)

**Comment by Hoju0216** [comment]
Hi Aniol

When I was debugging this program, I was also solving the problem of MS. Have you solved the problem? If you solved the problem, can you share your experience? Thank you so much!

Sincerely
Boju

**Comment by acivit** [comment]
Hi @Hoju0216, I did not solve the problem :) But I guess it has to be something related to changing the dimensions of the encoders-decoders (Not 100% sure about that).

I wish you luck!

Aniol
