### ISSUE TITLE
请问论文中Figure3是如何作出的呢？

### ISSUE THREAD

**Issue by DomineeringDragon** [cure-lab/SCINet#42]
在下在阅读论文时有个疑问，请问 Figure 3: The prediction results (Horizon = 48) of SCINet, Informer (Zhou et al. 2021), and TCN on randomly-selected sequencesfrom ETTh1 dataset. 里的这些预测的对比图是怎么作出的呢？

**Comment by ailingzengzzz** [comment]
Hi @DomineeringDragon,

We use **matplotlib** to plot the results. 
First, we save the output information for each method. Then, we load the output and plot them together via matplotlib.

**Comment by DomineeringDragon** [comment]
Thank you very much！
