### ISSUE TITLE
数据真实值输出问题

### ISSUE THREAD

**Issue by keyanxiaoba** [cure-lab/SCINet#69]
作者您好，感谢您提供的代码。我有一个问题想请教您一下，谢谢了。
我使用您提供的ETTh2数据集进行”M“多变量预测实验。在模型训练完成后，在您定义的测试函数中，有归一化的preds和trues，还有反归一化的true_scales和pred_scales。我将true_scales和pred_scales输出为.csv文件，以查看数据的大小。但是我发现输出的true_scales值在ETTh2数据集中并没有一样的，请问这是什么原因呢？下面图片标红的部分是我输出为.csv文件的指令。
![image](https://user-images.githubusercontent.com/131326812/233373297-c997047c-eee1-4619-99cf-ae221b867adf.png)

**Comment by gpzh** [comment]
最后解决了吗 ？我也出现了这个问题
