### ISSUE TITLE
Confusion about results of ETT dataset 

### ISSUE THREAD

**Issue by MatthewYZhang** [cure-lab/SCINet#7]
Hello all,

Thanks for your reply in the previous issue. I found that in your paper, in the table of performance on ETT dataset, you mark that LSTNet's MAE on ETTm1 (with horizon 24) is L1700, which is not a number. I am not sure what this means, because I believe that LSTNet didn't implement experiments on ETT dataset, and you didn't mention that if you re-implement LSTNet on your own. 

Thanks.

Matthew

**Comment by AlexMinhao** [comment]
Sorry, it is a typo. The results of the LSTNet can be referred from the paper of the Informer.
