### ISSUE TITLE
Hello, when I use my own dataset, the following error will be displayed

### ISSUE THREAD

**Issue by zulihit** [cure-lab/SCINet#9]
ValueError: __len__() should return >= 0
![image](https://user-images.githubusercontent.com/68625084/142102386-5deb2291-a471-4a1a-809b-dce86c6ace8a.png)
The data format I use is similar to ETT, but It's a lot less in the number of rows. What should I do？
Thanks a lot.

**Comment by VEWOXIC** [comment]
Hi, there. Can you please post the full error log of python? Which should start with `Traceback (most recent call last): `. We cannot tell what happened according to the `ValueError: len() should return >= 0`. Thanks a lot.
